### ISSUE TITLE
Extend Utilities and Testing to Perform Snapshots

### ISSUE THREAD

**Issue by NyanKiyoshi** [NyanKiyoshi/pytest-django-queries#42]
**Is your feature request related to a problem? Please describe.**
We would like to be able to record a bench session to generate snapshot files to be able to compare diffs and analyze SQL queries and query count.

**Describe the solution you'd like**
Generate a snapshot per test per module. This would be in a YAML format in order to make it more readable (human-friendly) for pull request reviewers but also for developers locally.

We would also include EXPLAIN queries, as part of #41.

We would include:
- The SQL query without the values – allows to detect issues and huge amount of parameters
- The query count in the root (top)

Which would look something like:
```yaml
count: 12
queries:
  - sql: >
      SELECT foo FROM bar WHERE id IN (?, ?, ?, ?, ?, ?)
```
